import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';

const MainContainer = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <Link href={'/'}>
          <a className={styles.navlink}>Home</a>
        </Link>
        <Link href={'/users'}>
          <a className={styles.navlink}>List of User</a>
        </Link>
      </nav>
      <div>{children}</div>
    </>
  );
};

export default MainContainer;
